### ISSUE TITLE
question on results of bag file

### ISSUE THREAD

**Issue by rnunziata** [m4nh/skimap_ros#15]
I am running the taigo_bar bag file in two ways.
First as given and everything works fine....I publish the pose from world to the optical frame. Map looks good all very good.

Then I have the same bag file where I removed all messages except for the depth and image messages . But when I run against it the map is all over the place and does not appear correct. This is not just a rotation issue...the map is clearly wrong.

Why would that happen. Why is the rgb image, depth image and pose not enough to correctly build the map?  Does the depth and image have different poses?  I am stuck on this results.  If you can help me out with an explanation that would great...maybe hint to how to work this issue.

**Comment by m4nh** [comment]
@rnunziata  sorry Richard unfortunatelly i have to remind you that you can't open random issue for your problems! The issue is something related with code itself, bugs or missing features... is not a tutorial for building your own code here , sorry.
