### ISSUE TITLE
Cannot show the octomap

### ISSUE THREAD

**Issue by YiChenCityU** [m4nh/skimap_ros#19]
![picture1](https://user-images.githubusercontent.com/12424523/39235264-06c83dfa-48a8-11e8-903c-84b25b38c4e7.png)
Hi, m4nh

I have run the demo, but cannot see the octomap. Do you have any idea?
Thanks very much.

**Comment by m4nh** [comment]
Hi @YiChenCityU .. obviously you cannot see Octomap because this is Skimap.. :) Jokes aside i need to see your console log to understand what's happening under the hood here. Thanks

**Comment by YiChenCityU** [comment]
Haha, I really skipped the skimap_live.launch step ( maybe just want to respect the system name). 
![kazam_screenshot_00005](https://user-images.githubusercontent.com/12424523/39283545-578d0d6c-4941-11e8-8c24-b069d74fcdfc.png)
Thanks very much.
