### ISSUE TITLE
The Problems When Plug in the ORB SLAM2

### ISSUE THREAD

**Issue by PWN0N** [m4nh/skimap_ros#2]
Hi, thanks for offering the great project! I'm newbie at ROS, when I trying to plug skimap into Orb slam2, I don't know where  to add the code to trans the point and senser data to skimap, any advice will be helpful! Thanks!

**Comment by m4nh** [comment]
Hi @PWN0N , in the section about Skimap Map Service:
https://github.com/m4nh/skimap_ros#skimap-service-skimap_map_servicelaunch
is described how use the off-the-shelf Ros Service to integrate new points from another node without import Skimap Library. Have you checked it?
