### ISSUE TITLE
Global Status:Fixed Frame    No tf data.  Actual error: Fixed Frame [odom] does not exist

### ISSUE THREAD

**Issue by wmj1238** [m4nh/skimap_ros#23]
Hi @m4nh  ,
When I use other dataset to run the skimap_ros, this issue is occoured in rviz. You have said that we should launch a TF LIstener in the skimap node,but I cannot know how to do that . Can you describe how to do it  in detail ?
Thank you very much .

**Comment by m4nh** [comment]
sorry @wmj1238  but unfortunatelly this is not a tutorial about ros :) i suggesto to read the default ROS tutorial about TFs ([TfBroadcaster](http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20broadcaster%20%28C%2B%2B%29)). However i think the problem in your case is just a matter of nomenclature. Be sure to have a Fixed World TF and a moving TF produced by a generic camera tracker (that could be also the robot odometry) and set those two TF names in the launch file.

**Comment by wmj1238** [comment]
Thanks again, I have just come into contact with this knowledge, so I don’t know much about it. I’ll go and see related tutorials first.

**Comment by fangzhangyun** [comment]
@wmj1238 I can't get the correct octomap in TUM dataset ,did you solve this problem ? I am looking forward your answer.
