### ISSUE TITLE
Iterate over occupancy in map cells

### ISSUE THREAD

**Issue by brunoeducsantos** [m4nh/skimap_ros#29]
Hi,
I was trying to understand how to iterate over map grid and get cell occupancy, but I couldn't understand from SkiMap header file. Could you point me out how can i proceed?
Thanks a lot.
Regards,
Bruno

**Comment by m4nh** [comment]
@BrunoEduardoCSantos hi, in the "skimap_live.cpp" example there is everything you need. With the following lines:

```
std::vector<Voxel3D> voxels;
map->fetchVoxels(voxels);
```
it is possible to fill a vector with all voxels in the map, and use this list to do you computation as well

>

**Comment by brunoeducsantos** [comment]
Thanks a lot @m4nh :+1:
