### ISSUE TITLE
2D grid visualization

### ISSUE THREAD

**Issue by brunoeducsantos** [m4nh/skimap_ros#30]
Hi @m4nh ,
I want to make a 2D grid visualization of occupied tiles using my SLAM mapping.
It is important to mention that there is a transformation of axis to match this SLAM reference frame:
- x-> y
- y -> z
- z->x 
```

  for (int i = 0; i < tiles.size(); i++) {

  
    geometry_msgs::Point point;
    point.x = tiles[i].y;
    point.y = tiles[i].z;
    point.z = tiles[i].x;

 
    std_msgs::ColorRGBA color;
    if (tiles[i].data != NULL) {
      color.r = color.g = color.b =
          tiles[i].data->w >= min_voxel_weight_ ? 0.0 : 1.0;
      color.a = 1;
    } else {
      color.r = color.g = color.b = 1.0;
      color.a = 1;
    }

    voxels_marker.points.push_back(point);
    voxels_marker.colors.push_back(color);
  }
```

I changed the coordinates, although I obtain a wrong 2D grid. 

![2dgridskimap](https://user-images.githubusercontent.com/3111976/47572398-c286b380-d932-11e8-84e2-e91d59aec7a3.png)

Could you point me out what could be my issue?
Thanks a lot in advance,
Bruno
PS: The grey stripes are the 2D grid

**Comment by m4nh** [comment]
It is very difficult for me to answer such detailed questions about your software :) however, in "skimap_live.cpp" there is also an example of how to view the Tiles of the corresponding 2D grid. It would be good to take a look at all the examples provided, so you can understand what you can already do with Skimap, and what should be implemented again.
