### ISSUE TITLE
2.5 D Map

### ISSUE THREAD

**Issue by brunoeducsantos** [m4nh/skimap_ros#32]
Hi @m4nh ,
Is there any example how to build 2.5 D map? 
I was trying to use 2D grid z coordinate as elevation, but this is constant. Can you help please?
Thanks,
Bruno

**Comment by m4nh** [comment]
Hi @BrunoEduardoCSantos, unfortunatelly this is not a community :) .. the Issue tab can't be used to propose new features.. so i can't help you anymore with your code, sorry.
