### ISSUE TITLE
Bag file download via Mega service

### ISSUE THREAD

**Issue by AndreaIncertiDelmonte** [m4nh/skimap_ros#4]
Hi,
the Mega cloud service that is hosting the bag file has a 2 GB data traffic limit per IP so is not possible download the file without paying the service.
Could you please share the bag file through another cloud service?
Tnks
Andrea

**Comment by m4nh** [comment]
@AndreaIncertiDelmonte moved bag file to other hosting service! Try it now

**Comment by AndreaIncertiDelmonte** [comment]
@m4nh thanks for your support!
