### ISSUE TITLE
About include files

### ISSUE THREAD

**Issue by GilgameshD** [m4nh/skimap_ros#5]
when I am using this package, I find that there is no file called <skimap_ros/SkimapIntegrationService.h>, but it is included in one head file.
So I don't know where to find it.

**Comment by m4nh** [comment]
@GilgameshD 
This is the ROS Service auto generated file from:

> add_service_files(
>   FILES
>   SkimapIntegrationService.srv
> )

are there any errors/warnings in  "catkin_make" command ?

**Comment by m4nh** [comment]
@GilgameshD  issue now is resolved. Please confirm it if you can

**Comment by GilgameshD** [comment]
I am sorry that I am not familiar with ROS, and thanks for you help. I will close the issue now.
